[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
solc_version = '0.8.15'

rpc_endpoints = { MAINNET = "${MAINNET_RPC}", ARBITRUM = "${ARBITRUM_RPC}", UNIT_TESTS = "https://rpc.tenderly.co/fork/eb4cc00e-c12c-45f5-905a-04f0cfdefa2f", TENDERLY = "https://rpc.tenderly.co/fork/f04aafd5-a74b-4c13-9b1e-e0962cb2d303" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config