[default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
remappings = [
    
    '@yield-protocol/utils-v2=lib/yield-utils-v2/',
    '@yield-protocol/vault-interfaces=lib/vault-interfaces/',
    '@yield-protocol/yieldspace-tv=lib/yieldspace-tv/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config