[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
solc_version = '0.8.15'

rpc_endpoints = { MAINNET = "${MAINNET_RPC}", ARBITRUM = "${ARBITRUM_RPC}", UNIT_TESTS = "https://rpc.tenderly.co/fork/80702a3d-f55f-4168-9d6d-954878f7240a", TENDERLY = "https://rpc.tenderly.co/fork/6c5d4b71-8bf2-4a56-90eb-7fd26e2dfe35" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config