[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
solc_version = '0.8.15'

rpc_endpoints = { mainnet = "${ALCHEMY_MAINNET_RPC}", tenderly = "https://rpc.tenderly.co/fork/f33e0466-9ad7-4274-bc11-8aa09179ea80" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config