[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
solc_version = '0.8.15'

rpc_endpoints = { MAINNET = "${MAINNET_RPC}", ARBITRUM = "${ARBITRUM_RPC}", TENDERLY = "https://rpc.tenderly.co/fork/b1ef7daa-73f0-4558-8502-b0b501b1ab9a" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config